[default]
    APPNAME = "Huntotron"
    VERSION = "0.2.1"

    DATABASE_PORT = "5432"
    DATABASE_USER = "postgres"
    DATABASE_PASSWORD = "postgres"
    DATABASE_DB = "huntotron"
    DATABASE_HOST = "localhost"
    DATABASE_ECHO_MODE = false

    MAIN_CHARACTER_ID = 0
    # this app is not build to use many users
    # so we just hardcode myself in there


[test]
    DATABASE_DB = "test-db"
    DATABASE_HOST = "postgres"
